name: Awesome Bot
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Awesome Bot
      run: gem install awesome_bot

    - name: Run Awesome Bot
      run: awesome_bot README.md --request-delay 1 --allow-dupe --white-list oreilly.com,youtube.com

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ab-results
        path: ab-results-README.md-filtered.json
